name: ModerrkowoCore
version: 1.0
main: pl.moderr.moderrkowo.core.Main
api-version: 1.16
authors: [ MODERR ]
softdepend: [ ModerrkowoDB, WorldGuard ]
commands:
  alogi:
    permission: moderr.admin
  tpa:
    permission: moderr.player
  tpdeny:
    permission: moderr.player
  tpaccept:
    permission: moderr.player
  pogoda:
    permission: moderr.player
    aliases: [weather]
  helpop:
    permission: moderr.player
  ahelpop:
    permission: moderr.admin
  adminchat:
    permission: moderr.admin
    aliases: [ ac,achat ]
  invsee:
    permission: moderr.admin
  sendalert:
    permission: moderr.admin
    aliases: [ awyslijwiadomosc ]
  msg:
    permission: moderr.player
    aliases: [ message,wiadomosc,pv,whisper ]
  reply:
    permission: moderr.player
    aliases: [ odpowiedz,r ]
  home:
    description: Komenda do prze teleportowania się do domu
    permission: moderr.player
    aliases: [ dom ]
  sethome:
    description: Komenda do ustawienia domu
    permission: moderr.player
    aliases: [ ustawdom ]
  dzialka:
    description: Komenda do zarządzania działką
    permission: moderr.player
    aliases: [ cuboid ]
  chat:
    description: Komenda do ustawien chatu
    permission: moderr.admin
  rynek:
    description: Otwiera ekwipunek z rynkiem między graczami
    permission: moderr.player
    aliases: [ah]
  say:
    description: Komenda do mówienia jako Administracja
    permission: moderr.admin
  regulamin:
    description: Pokazuje regulamin
    permission: moderr.player
  discord:
    description: Komenda do zaproszenia na Discordzie
    permission: moderr.player
  mkick:
    description: Komenda do wyrzucenia gracza
    permission: moderr.admin
  craftingdzialki:
    description: Komenda do pokazania craftingu dzialki
    permission: moderr.player
  endersee:
    description: Komenda do podejrzenia skrzyni kresu graczy
    permission: moderr.admin
  spawn:
    description: Komenda do teleportacji na spawna
    permission: moderr.player
  setspawn:
    description: Komenda do ustawiania spawna
    permission: moderr.admin
  vanish:
    description: Komenda do ukrycia się przed graczami
    permission: moderr.admin
  villager:
    description: Komenda do postawienia villagerów
    permission: moderr.admin
  nazwa:
    description: Komenda do ustawienia nazwy przedmiotui
    permission: moderr.admin
  abank:
    permission: moderr.admin
  przelej:
    permission: moderr.player
  topka:
    permission: moderr.player
  mban:
    permission: moderr.admin
  gamemode:
    permission: moderr.admin
  fly:
    permission: moderr.admin
  sidebar:
    permission: moderr.player
  drop:
    permission: moderr.admin
  unactiveallquest:
    permission: moderr.admin
permissions:
  moderr.admin:
    default: op
  moderr.player:
    default: true
  moderr.cuboids.admin:
    default: op